# Generated by Django 3.1.7 on 2021-03-25 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreg',
            name='birth_place',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userreg',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 25, 15, 15, 45, 673871), null=True),
        ),
    ]
